#!/usr/bin/env bash
# internal/data/popular-gomod.json is a MANUALLY curated list, unlike the other
# refresh-popular-*.sh scripts.
#
# npm, PyPI, and crates.io all expose a public download-count/popularity API
# (registry.npmjs.org's downloads endpoint, the top-pypi-packages dataset,
# crates.io's own "sort=downloads"), so those lists are machine-generated by
# ranking real usage. The Go module proxy protocol (proxy.golang.org) has no
# such endpoint — it only serves @latest/@v/list/@v/<version>.{info,mod,zip}
# for a module you already know the path of, with no discovery or ranking
# surface. There is also no single canonical "most popular Go modules" feed
# comparable to hugovk's top-pypi-packages dataset.
#
# So popular-gomod.json is hand-maintained: well-known, widely-imported modules
# from the standard-library extension packages (golang.org/x/...) and the most
# commonly used third-party libraries in the Go ecosystem (web frameworks, CLI
# tooling, testing, cloud SDKs, ORMs, observability). To refresh it:
#
#   1. Browse https://pkg.go.dev/ (per-package "Imported By" counts) and
#      https://github.com/avelino/awesome-go for currently-popular modules.
#   2. Add/remove entries in internal/data/popular-gomod.json by hand, keeping
#      the list sorted and deduplicated.
#   3. Every entry MUST be a real, currently-published module path — verify
#      with: curl -fsS "https://proxy.golang.org/<module>/@latest"
#
# This script only sorts/dedupes/validates the JSON you've already edited; it
# does not fetch names from anywhere (there is nowhere to fetch them from).
set -euo pipefail
out=internal/data/popular-gomod.json
python3 - "$out" <<'PY'
import json, sys
path = sys.argv[1]
names = json.load(open(path))
names = sorted(set(names))
json.dump(names, open(path, "w"), indent=2)
open(path, "a").write("\n")
print(f"normalized {len(names)} gomod names in {path}")
PY
